name: CD Pipeline

on:
  push:
    branches:
      - prod

env:
  IMAGE_NAME: intranet-newdeal
  IMAGE_TAG: latest
  DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:

  # =========================
  # JOB 1 : SCAN SECURITE
  # =========================
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Scan sécurité
        run: |
          echo "Scan OK"

  # =========================
  # JOB 2 : DEPLOY
  # =========================
  deploy:
    runs-on: runner_prod   # ⚠️ ou ubuntu-latest si tu n’as pas de runner
    needs: scan

    steps:
      - name: Login DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: |
          docker pull $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Stop container
        run: |
          docker stop intranet || true

      - name: Remove container
        run: |
          docker rm intranet || true

      - name: Run container
        run: |
          docker run -d -p 80:80 --name intranet \
          $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG